global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'vdw-orchestrator'
    static_configs:
      - targets: ['vdw-orchestrator:8000']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
